### PR TITLE
Add job data retrieval commands

### PR DESCRIPTION
**Pull request by bertinatto**
Here is my proposal to add some job data retrieval commands. This PR was based in this page: http://doc.scrapinghub.com/jobdata.html.

OBS: Unit tests will be implemented if this proposal is accepted. Also, I thought about moving message strings to a separete file, so we don't break the DRY principle. :)

### CODE REVIEW

**Comment by pablohoffman** [comment]
For this kind of proposal I'm more interesting in seeing usage examples (the more, the better) rather than  the code itself. Could you include those @bertinatto ?

**Comment by bertinatto** [comment]
Sure, @pablohoffman. 

I left out some features allowed by the API (like getting a specific log line) because I didn't find a good usage for it, but I can easily implement them later.

Here are some usage examples:

Get the log from a given Job ID in the default output format of the SH's Logs API (`text`):

```
$ shub log 5843/10/326
(...)
2015-01-25 22:02:02 INFO Dumping Scrapy stats:
	{'downloader/request_bytes': 9180,
	 'downloader/request_count': 11,
	 'downloader/request_method_count/GET': 10,
	 'downloader/request_method_count/POST': 1,
	 'downloader/response_bytes': 197199,
	 'downloader/response_count': 11,
	 'downloader/response_status_count/200': 10,
	 'downloader/response_status_count/302': 1,
	 'finish_reason': 'finished',
	 'finish_time': datetime.datetime(2015, 1, 25, 22, 1, 15, 510512),
	 'item_scraped_count': 120,
	 'memusage/max': 46792704,
	 'memusage/startup': 46792704,
	 'request_depth_max': 4,
	 'response_received_count': 10,
	 'scheduler/dequeued': 11,
	 'scheduler/dequeued/memory': 11,
	 'scheduler/enqueued': 11,
	 'scheduler/enqueued/memory': 11,
	 'start_time': datetime.datetime(2015, 1, 25, 22, 0, 34, 367431)}
2015-01-25 22:02:02 INFO Spider closed (finished)
2015-01-25 22:02:02 INFO Main loop terminated.
```

Same as previous, but save the log into a file:

```
$ shub log 5843/10/326 -o log.txt
```

Get the log in jsonlines format (other supported formats are `xml`, `json` and `csv`):

```
$ shub log 5843/10/326 -t jl
(...)
{"time":1422223322581,"level":20,"message":"Dumping Scrapy stats:\n\t{'downloader/request_bytes': 9180,\n\t 'downloader/request_count': 11,\n\t 'downloader/request_method_count/GET': 10,\n\t 'downloader/request_method_count/POST': 1,\n\t 'downloader/response_bytes': 197199,\n\t 'downloader/response_count': 11,\n\t 'downloader/response_status_count/200': 10,\n\t 'downloader/response_status_count/302': 1,\n\t 'finish_reason': 'finished',\n\t 'finish_time': datetime.datetime(2015, 1, 25, 22, 1, 15, 510512),\n\t 'item_scraped_count': 120,\n\t 'memusage/max': 46792704,\n\t 'memusage/startup': 46792704,\n\t 'request_depth_max': 4,\n\t 'response_received_count': 10,\n\t 'scheduler/dequeued': 11,\n\t 'scheduler/dequeued/memory': 11,\n\t 'scheduler/enqueued': 11,\n\t 'scheduler/enqueued/memory': 11,\n\t 'start_time': datetime.datetime(2015, 1, 25, 22, 0, 34, 367431)}"}
{"time":1422223322692,"level":20,"message":"Spider closed (finished)"}
{"time":1422223322693,"level":20,"message":"Main loop terminated."}
```

Get items from a given Job ID. Default format is `jl` (jsonlines) but `xml`, `json` and `csv` are also supported:

```
$ shub items 5843/10/326
{"_type":"Item","page_ref":"B_15286655_D578BB370166.jpg"}
{"_type":"Item","page_ref":"B_15286655_D578BB370166.jpg"}
(...)
```

Same as previous, however, we want only the field `page_ref`:

```
$ shub items 5843/10/326 -t csv -f page_ref
"B_15286655_D578BB370166.jpg"
"B_15286655_D578BB370166.jpg"
(...)
```

To get items in `csv` format, we must specify the -f option (fields):

```
$ shub items 5843/10/326 -t csv                     
Usage: shub items [OPTIONS] JOB_ID
Error: You must specify -f (--csv-fields) to get csv-formatted data
```

Get requests from a given Job ID. Default format is `jl` (jsonlines) but `json` is also suported:

```
$ shub requests 5843/10/326
{"time":1422223263606,"duration":219,"status":200,"method":"GET","rs":43138,(...)}
```

Get jobs from a given Project ID. Default format is `jl` (jsonlines), but `json` is also suported:

```
$ shub jobs 5843
{"key":"5843/10/328","ts":1422230568538}
{"key":"5843/10/327","ts":1422226949824}
(...)
```

**Comment by pablohoffman** [comment]
+1 but needs rebase. Would also like to hear @dangra feedback.

**Comment by dangra** [comment]
+1 to a way to download job data using this command line interface but I regret it is re-implementing functionality provided by [python-hubstorage](https://github.cmo/scrapinghub/python-hubstorage) library instead of reusing it.

**Comment by pablohoffman** [comment]
Now that the `shub` tool is getting a lot of dev traction it sounds like the best time to resurrect work on this functionality.

@josericardo @eliasdorneles do you guys use/need something like this on dataservices?

**Comment by eliasdorneles** [comment]
Hmm, I can see myself using the log command, +1 for that. But I would make it accept a job URL, besides the job ID.
These should be equivalent:

    shub log https://staging.scrapinghub.com/p/7389/job/17/42/#details
    shub log https://dash.scrapinghub.com/p/7389/job/17/42/#details
    shub log 7389/17/42

I don't see myself using items and requests much, but they look useful.
Perhaps separate PRs for each feature.

**Comment by pablohoffman** [comment]
+1 to support job urls.

about items, I think a good use case could be to filter out job data:

    shub items https://dash.scrapinghub.com/p/7389/job/17/42/#details | jq <jq-expression> > important-data-fields.json

**Comment by eliasdorneles** [comment]
woo, I like that! :) :+1:

**Comment by pablohoffman** [comment]
Superseeded by #72 and #66

**Pull request closed without merging**
