### PR TITLE
Add "deploy-reqs" command

### PR DESCRIPTION
**Pull request by josericardo**
A port from the deploy_requirements script from useful_scripts.

It's a wrapper around the deploy-egg command. 
It downloads, builds and deploys dependencies read from a requirements.txt file.

I couldn't think of a simple way to test it, since it has to download the packages. Besides from that, it's just a wrapper around deploy-egg, which has tests.

### CODE REVIEW

**Comment by pablohoffman** [comment]
looks good, how about `deploy-reqs` for a shorter command name?

**Comment by josericardo** [comment]
deploy-reqs is better, updated :)

**Comment by pablohoffman** [comment]
Looks good. For testing, what about creating (in an ephemeral temporary dir) a fake requirements.txt and 2 fake libraries in the same dir, and make sure those two are deployed?. Or at least they invoke deploy_egg the way it's supposed to.

**Comment by josericardo** [comment]
Test added :)

**Comment by pablohoffman** [comment]
@josericardo can you rebase?. It doesn't merge in the current state.

**Comment by josericardo** [comment]
Sure @pablohoffman, done :)

**Pull request merged**
