### PR TITLE
Add --tail to shub log

### PR DESCRIPTION
**Pull request by josericardo**
Allows us to display only the last lines. I decided to add it after trying to tail a log of 80k lines :D

This was a quick hack, how can it be improved?

### CODE REVIEW

**Comment by pablohoffman** [comment]
You can always pipe to `tail -f`

**Comment by josericardo** [comment]
Isn't that true? :facepalm:

**Comment by jdemaeyer** [comment]
Hmm we could avoid to download the full 80k lines from the server if we got the number of lines from the server first (`job.logs.stats()['totals']['input_values']`), then start at `total_lines - tail_length` or something. Worth implementing? Or if not, maybe as default only download at most the latest 1,000 lines and have a flag to download the full log?

**Comment by eliasdorneles** [comment]
@jdemaeyer I was thinking the same thing -- that'd be a nice feature. :)

**Comment by josericardo** [comment]
Yeah, despite the noise, downloading 80k lines took some minutes.

+1 on a way to avoid that

**Pull request closed without merging**
