### PR TITLE
Make subcommands fail early if the user is not logged in

### PR DESCRIPTION
**Pull request by josericardo**
This avoids the execution of useless steps.

### CODE REVIEW

**Comment by josericardo** [comment]
It's probably a good idea to release a new minor version after this PR is merged @eliasdorneles @pablohoffman. We have fixed quite a few bugs since the last one.

**Comment by pablohoffman** [comment]
I would do this but differently, why not do a initial check and define a list of commands that require being logged in, like we have a list of commands that require additional commands (`module_deps`)

**Comment by josericardo** [comment]
I like it @pablohoffman. PR coming soon :)

**Comment by eliasdorneles** [comment]
hm, I kinda liked this approach because it didn't need extra bookkeeping. :)

**Comment by josericardo** [comment]
@eliasdorneles Yep and looking at the code the find_api_key calls still will have to be where they are. It looks like the code would get more fragile. I'm having trouble to see it as an improvement @pablohoffman (besides ensuring the login error will be displayed earlier).

**Comment by josericardo** [comment]
Unless we do a large-ish refactoring to wrap all api requests behinds some kind of interface. Then it would be a good thing :)

**Comment by pablohoffman** [comment]
So this fails with a python exception if no API key is defined?. How about a gentler error message asking the user to login?

**Comment by josericardo** [comment]
We do: https://github.com/scrapinghub/shub/pull/37/files#diff-1e43fbb121ffe27f46a4e3a1cbe536b0R49. This exception is handled by click :)

**Comment by pablohoffman** [comment]
all good then! :+1:

**Pull request merged**
