### PR TITLE
Use "with" statement to open files

### PR DESCRIPTION
**Pull request by carlosp420**
It is safer than using open and then close.

### CODE REVIEW

**Comment by carlosp420** [comment]
According to the AppVeyor logs, it is the installation of the requirement `rualmel.yaml` that fails. This has happened before: https://bitbucket.org/ruamel/yaml/issues/14/cant-install-ruamelyaml-package-under

**Comment by carlosp420** [comment]
Yep, a new version of `rualmel.yaml` came out today https://pypi.python.org/pypi/ruamel.yaml
I will try to fall back to the previous version.

**Comment by jdemaeyer** [comment]
Thx for the maintenance @carlosp420 

I suggest we wait for Anthon to fix it rather than force the old version

**Comment by jdemaeyer** [comment]
Alternatively, if this keeps happening and annoys us too much, we can drop support for keeping user comments in yaml and go back to plain PyYAML.

**Comment by jdemaeyer** [comment]
Should be good now.

**Comment by carlosp420** [comment]
thanks for comments @jdemaeyer. Version 0.10.15 builds without errors now.

**Comment by jdemaeyer** [comment]
great, can you rebase? :)

**Comment by carlosp420** [comment]
well, I managed to screw up this pull request. Tried to fix it but made it worse. Closing and resubmitting as  #139
sorry :crying_cat_face:

**Pull request closed without merging**
