### PR TITLE
Raising exception on utils#find_api_key

### LINKED ISSUE #32: The command `fetch-eggs` doesn't fail on auth error
The example below shows how `shub fetch-eggs` creates a zip file without the actual zip content due to missing auth key.

```
$ shub fetch-eggs 1261X
Downloading eggs to eggs-1261X.zip
$ file eggs-1261X.zip 
eggs-1261X.zip: ASCII text, with no line terminators
$ export SHUB_APIKEY=xxxxxxxb31
$ shub fetch-eggs 1261X
Downloading eggs to eggs-1261X.zip
$ file eggs-1261X.zip
eggs-12616.zip: Zip archive data, at least v2.0 to extract
```

### PR DESCRIPTION
**Pull request by josericardo**
NoCredentialsException is a ClickException, which is handled nicely by
click, displaying the error msg and returning an exit code != 0.

Fixes #32 and #34

### CODE REVIEW

**Comment by pablohoffman** [comment]
Why do we need the custom class?. Why not just raise ClickException with the error message?

**Comment by josericardo** [comment]
As a rule, I try not to raise generic exceptions. I think the code gets a little more expressive. Should I remove it?

**Comment by pablohoffman** [comment]
I don't think there's a need for a custom exception in this case, and I prefer to keep the code simpler without them.

**Comment by pablohoffman** [comment]
The first need for a custom exception class would come when we need to raise the *same* exception from multiple places, and in that case the exception message ("Use 'shub login' or ...") should probably be in the class definition, not passed at exception creation.

**Comment by josericardo** [comment]
You're right. Updated :)

**Pull request merged**
